# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Manuel Traut <manuel.traut@mt.com>

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-modules-pvc
spec:
  storageClassName: manual
  volumeName: vm-modules-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
